Public Enum TipoToken
    IDENTIFICADOR
    NUMERO
    CADENA
    PALABRA_RESERVADA
    TIPO_DATO
    ASIGNACION
    OPERADOR_ARITMETICO
    PARENTESIS_IZQUIERDO
    PARENTESIS_DERECHO
    FIN_LINEA
    FIN_ARCHIVO
    ERROR_404
End Enum